### ISSUE TITLE
MAPIR plugin: "Pre-Process Images From Directory" generate exception

### ISSUE THREAD

**Issue by yellowcox** [mapircamera/Fiji#1]
Hi,

When I use the MAPIR plugin to Pre-process my images from directory, the first image is processed, and after Fiji generate an exception:

Exception from Fiji :

(Fiji Is Just) ImageJ 2.0.0-rc-15/1.49k; Java 1.6.0_24 [64-bit]; Windows NT (unknown) 6.2; 19MB of 5989MB (<1%)
 
java.lang.IndexOutOfBoundsException: Index: 1, Size: 0

	at java.util.ArrayList.RangeCheck(ArrayList.java:547)

	at java.util.ArrayList.get(ArrayList.java:322)

	at Post_Process_Batch.run(Post_Process_Batch.java:273)

	at ij.IJ.runUserPlugIn(IJ.java:202)

	at ij.IJ.runPlugIn(IJ.java:166)

	at ij.Executer.runCommand(Executer.java:131)

	at ij.Executer.run(Executer.java:64)

	at java.lang.Thread.run(Thread.java:662)

Log from Fiji :

Input Directory: C:\Users\sebastien\Desktop\testmapir\
Output Directory: C:\Users\sebastien\Desktop\testmapirpreprocessed\
Images that will be proccessed: 
028.JPG
029.JPG
030.JPG
031.JPG
032.JPG
-----------------------------------------------------------------
I will begin to process the images mentioned above. Please wait.
Working Directory: C:\Users\SEBAST~1\DOWNLO~1\FIJI-W~3\FIJI-W~1\Fiji.app\
C:\Users\SEBAST~1\DOWNLO~1\FIJI-W~3\FIJI-W~1\Fiji.app\Survey2\EXIFTool\exiftool.exe
C:\Users\SEBAST~1\DOWNLO~1\FIJI-W~3\FIJI-W~1\Fiji.app\Survey2\EXIFTool\exiftool.exe "C:\Users\sebastien\Desktop\testmapir\028.JPG"
Windows NT (unknown)
Camera Model for C:\Users\sebastien\Desktop\testmapir\028.JPG: Survey2_NDVI
Processing: C:\Users\sebastien\Desktop\testmapir\028.JPG
path_ff=C:\Users\SEBAST~1\DOWNLO~1\FIJI-W~3\FIJI-W~1\Fiji.app\Survey2\Flat-Fields\ndvi\ndvi.JPG|path_jpg=C:\Users\sebastien\Desktop\testmapir\028.JPG|path_out=C:\Users\sebastien\Desktop\testmapirpreprocessed\|filter_radius=10
path_ff: C:\Users\SEBAST~1\DOWNLO~1\FIJI-W~3\FIJI-W~1\Fiji.app\Survey2\Flat-Fields\ndvi\ndvi.JPG
path_jpg: C:\Users\sebastien\Desktop\testmapir\028.JPG
path_out: C:\Users\sebastien\Desktop\testmapirpreprocessed\
filter_radius: 10

I use the last package http://www.docs.peauproductions.com/fiji/fiji-win64-20160714.zip

Thx for your help

**Comment by yellowcox** [comment]
Hi, same trouble with the the version of the 19-07-2016: http://www.docs.peauproductions.com/fiji/fiji-win64-20160719.zip

Tested with Windows 10 and Windows 7 64bits

**Comment by mapircamera** [comment]
Hi,

What does your input directory look like? The plugin assumes that your directory structure contains a RAW followed by JPG for all images. Changing this structure might cause the plugin to produce an error.

**Comment by yellowcox** [comment]
Hi,

OK I try RAW+JPEG and it's working :-)
So there is no pre-processing for JPEG only?
Thx

**Comment by mapircamera** [comment]
Yes there is pre-processing for JPGs, but we never recommend using JPGs
(only to copy the EXIF info over to the TIFFs). If you need JPGs you can
convert the TIFFs to JPGs in the calibration step.

*Peau Productions, Inc*
Toll Free:* +1 (877) 949-1684 <%2B1%20%28877%29%20949-1684>*
Local*: +1 (619) 554-8848 <%2B1%20%28619%29%20554-8848%20x103>*
7592 Metropolitan Dr
Suite 401
San Diego CA 92108 USA
www.peauproductions.com
www.mapir.camera

Skype: peauproductions
Youtube: PeauProductions <http://www.youtube.com/user/PeauProductions>
Facebook: PeauProductions
<https://www.facebook.com/pages/Peau-Productions/287830910468>

**Comment by mapircamera** [comment]
Fixed this issue that was only happening with jpg.
