### ISSUE TITLE
Corrupt ZIP

### ISSUE THREAD

**Issue by jdzurisin** [mapircamera/Fiji#2]
Hi there. I've tried downloading both 32 and 64 bit versions and opening with both windows native unzipper and winrar and ever time it says that the packages are corrupt. Any ideas?

**Comment by mapircamera** [comment]
Hi,

I new version has been release, give it a try! Also, try unzipping with 7zip as that is what I used to zip it. It should work fine with Windows native unzipper because it is compressed as .zip, but if not I'll have to revert to the Windows native zipper from now on.
